services:
  postgres:
    image: postgres:16.0
    restart: always
    env_file:
      - .env
  elastic_search:
    image: elasticsearch:8.6.2
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  etl_service:
    build:
      context: .
      dockerfile: postgres_to_es/Dockerfile
  